# Generated by Django 3.1.7 on 2021-02-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='editDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('isDelete', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('editDate', models.DateTimeField(auto_now=True, null=True)),
                ('link', models.FilePathField()),
                ('type', models.CharField(max_length=10)),
                ('idTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsite.topic')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsite.user')),
            ],
        ),
    ]
