# Generated by Django 3.1.7 on 2021-03-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
