# Generated by Django 3.1.7 on 2021-03-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0002_auto_20210309_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='idUser',
        ),
    ]
