# Generated by Django 3.1.7 on 2021-03-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0003_remove_document_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
