# Generated by Django 3.1.7 on 2021-02-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0004_auto_20210223_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
