# Generated by Django 3.1.7 on 2021-02-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0006_auto_20210223_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='idUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
