# Generated by Django 3.1.7 on 2021-02-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0008_auto_20210228_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
