# Generated by Django 3.1.7 on 2021-02-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsite', '0009_auto_20210228_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
